### ISSUE TITLE
Публичная и приватная части класса

### ISSUE THREAD

**Issue by avasyukov** [turfe/iterations#1]
В публичной части класса должна остаться только реализация интерфейса. Остальное должно уехать в protected или private.

(Приличную горку функций, которые лежат рядом и обеспечивают всю реальную работу со списком, тоже очень тянет сделать приватными методами. Но тут можно уже сдержаться, в принципе. Но хотя бы публичную часть класса привести к фэн-шуйному виду точно нужно.)

**Comment by turfe** [comment]
Закомитил изменения, вроде все изменил по описанию

**Comment by avasyukov** [comment]
Подтверждаю, решено
